# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.2 on 2017-06-10 22:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
=======
# Generated by Django 1.11.2 on 2017-06-12 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> 99d74667a5f705f11392ac5f4cd489ac965a0b48


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
<<<<<<< HEAD
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 6, 10, 22, 20, 46, 109378, tzinfo=utc))),
=======
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
>>>>>>> 99d74667a5f705f11392ac5f4cd489ac965a0b48
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 6, 10, 22, 20, 46, 108878, tzinfo=utc))),
=======
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
>>>>>>> 99d74667a5f705f11392ac5f4cd489ac965a0b48
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problems.Problem'),
        ),
    ]
