# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 22, 21, 30, 868876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 10, 22, 21, 30, 867875, tzinfo=utc)),
        ),
    ]
