# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
