# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'replies'},
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='approved_comment',
            new_name='approved_reply',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='post',
            new_name='comment',
        ),
    ]
