# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='rootproblem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subproblems', to='problems.Problem'),
        ),
    ]
