# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20170623_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='rootproblem',
            new_name='root_problem',
        ),
    ]
