# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20170618_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='rootproblem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subproblems', to='problems.Problem'),
        ),
    ]
