# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20170616_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='problem',
        ),
    ]
