# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0004_auto_20170623_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('depth', models.IntegerField(default=0)),
                ('downvotes', models.ManyToManyField(related_name='why_downvotes', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whys', to='problems.Problem')),
                ('upvotes', models.ManyToManyField(related_name='why_upvotes', to=settings.AUTH_USER_MODEL)),
                ('why_requests', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problems.Problem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='why',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problems.Why'),
        ),
    ]
