# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0005_auto_20170626_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='why_requests',
            field=models.ManyToManyField(related_name='problem_why_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='why',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
