# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_anonymous_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='liked',
        ),
    ]
