# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20170626_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='why',
            name='has_descendent',
            field=models.BooleanField(default=False),
        ),
    ]
