# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20170622_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='rootproblem',
        ),
        migrations.AddField(
            model_name='problem',
            name='rootproblem',
            field=models.ManyToManyField(blank=True, null=True, related_name='subproblems', to='problems.Problem'),
        ),
    ]
