# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_auto_20170623_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='subproblem',
            field=models.ManyToManyField(blank=True, related_name='rootproblems', to='problems.Problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rootproblem',
            field=models.ManyToManyField(blank=True, related_name='subproblems', to='problems.Problem'),
        ),
    ]
