# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_why_has_descendent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_problem_comment',
            field=models.BooleanField(default=False),
        ),
    ]
