# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_auto_20170623_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='rootproblem',
            field=models.ManyToManyField(blank=True, related_name='_problem_rootproblem_+', to='problems.Problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='subproblem',
            field=models.ManyToManyField(blank=True, related_name='_problem_subproblem_+', to='problems.Problem'),
        ),
    ]
