# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20170623_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='rootproblem',
        ),
        migrations.AddField(
            model_name='problem',
            name='rootproblem',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='subproblems', to='problems.Problem'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='subproblem',
        ),
        migrations.AddField(
            model_name='problem',
            name='subproblem',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='rootproblems', to='problems.Problem'),
        ),
    ]
